Update continuous_integration.yml

diff --git a/.github/workflows/continuous_integration.yml b/.github/workflows/continuous_integration.yml
--- a/.github/workflows/continuous_integration.yml
+++ b/.github/workflows/continuous_integration.yml
@@ -27,7 +27,7 @@ jobs:
               run: cmake --build ./build --config Release
 
     linting:
-        runs-on: windows-latest
+        runs-on: ubuntu-latest
 
         steps:
             - uses: actions/checkout@v4
@@ -42,21 +42,21 @@ jobs:
               if: success() || failure()
               run: npx prettier . --check
 
-            - name: Show diff
-              if: success() || failure()
-              run: |
-                  npx prettier . --write
-                  git diff -- . ':(exclude)package-lock.json' ':(exclude)package.json' > diff.txt
-                  npm install -g diff2html-cli
-                  diff2html -s side -F diff.html
+            # - name: Show diff
+            #   if: success() || failure()
+            #   run: |
+            #       npx prettier . --write
+            #       git diff -- . ':(exclude)package-lock.json' ':(exclude)package.json' > diff.txt
+            #       npm install -g diff2html-cli
+            #       diff2html -s side -F diff.html
 
-            - name: Upload html diff
-              if: success() || failure()
-              uses: actions/upload-artifact@v4
-              with:
-                  name: HTML Diff
-                  path: diff.html
-                  retention-days: 3
+            # - name: Upload html diff
+            #   if: success() || failure()
+            #   uses: actions/upload-artifact@v4
+            #   with:
+            #       name: HTML Diff
+            #       path: diff.html
+            #       retention-days: 3
 
             - name: Run PSScriptAnalyzer (for PowerShell linting)
               if: success() || failure()
