Update continuous_integration.yml

diff --git a/.github/workflows/continuous_integration.yml b/.github/workflows/continuous_integration.yml
--- a/.github/workflows/continuous_integration.yml
+++ b/.github/workflows/continuous_integration.yml
@@ -13,7 +13,7 @@ jobs:
             matrix:
                 os:
                     # - macos-latest
-                    - ubuntu-latest
+                    - ubuntu-24.04
                     # - windows-latest
 
         runs-on: ${{ matrix.os }}
@@ -72,42 +72,42 @@ jobs:
                   Write-Host "-------------"
 
                   Import-Module ./scripts/Linters.psm1
-                  Test-TerminalGamesCode -Verbose"
+                  Test-TerminalGamesCode -Verbose
 
             - name: Build Project
               run: cmake --build ./build --config Release
 
-    linting:
-        strategy:
-            matrix:
-                os:
-                    - macos-latest
-                    - ubuntu-latest
-                    - windows-latest
+    # linting:
+    #     strategy:
+    #         matrix:
+    #             os:
+    #                 - macos-latest
+    #                 - ubuntu-latest
+    #                 - windows-latest
 
-        runs-on: ${{ matrix.os }}
+    #     runs-on: ${{ matrix.os }}
 
-        steps:
-            - uses: actions/checkout@v4
+    #     steps:
+    #         - uses: actions/checkout@v4
 
-            - name: Install linting dependencies
-              run: npm install
+    #         - name: Install linting dependencies
+    #           run: npm install
 
-            - name: Run cspell
-              run: npx cspell .
+    #         - name: Run cspell
+    #           run: npx cspell .
 
-            - name: Run prettier (for JSON linting)
-              if: success() || failure()
-              run: npx prettier . --check
+    #         - name: Run prettier (for JSON linting)
+    #           if: success() || failure()
+    #           run: npx prettier . --check
 
-            - name: Run PSScriptAnalyzer (for PowerShell linting)
-              if: success() || failure()
-              shell: pwsh
-              run: Invoke-ScriptAnalyzer -Path . -Recurse -Severity Information
+    #         - name: Run PSScriptAnalyzer (for PowerShell linting)
+    #           if: success() || failure()
+    #           shell: pwsh
+    #           run: Invoke-ScriptAnalyzer -Path . -Recurse -Severity Information
 
-            - name: Run gitattributes linter
-              if: success() || failure()
-              shell: pwsh
-              run: |
-                  Import-Module ./scripts/Linters.psm1
-                  Test-GitAttributesFile -Verbose
+    #         - name: Run gitattributes linter
+    #           if: success() || failure()
+    #           shell: pwsh
+    #           run: |
+    #               Import-Module ./scripts/Linters.psm1
+    #               Test-GitAttributesFile -Verbose
