more changes

diff --git a/.github/workflows/ContinuousIntegration.yml b/.github/workflows/ContinuousIntegration.yml
--- a/.github/workflows/ContinuousIntegration.yml
+++ b/.github/workflows/ContinuousIntegration.yml
@@ -63,47 +63,47 @@ jobs:
                   Import-Module ./modules/TerminalGames.psd1
                   Install-LintingDependencies -Platform "${{ matrix.os }}" -Verbose
 
-            - name: Run gitignore linter
-              if: (success() || failure()) && steps.dependencies.outcome == 'success'
-              run: |
-                  Import-Module ./modules/TerminalGames.psd1
-                  Test-GitIgnoreFile -Verbose
+            # - name: Run gitignore linter
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success'
+            #   run: |
+            #       Import-Module ./modules/TerminalGames.psd1
+            #       Test-GitIgnoreFile -Verbose
 
-            - name: Run gitattributes linter
-              if: (success() || failure()) && steps.dependencies.outcome == 'success'
-              run: |
-                  Import-Module ./modules/TerminalGames.psd1
-                  Test-GitAttributesFile -Verbose
+            # - name: Run gitattributes linter
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success'
+            #   run: |
+            #       Import-Module ./modules/TerminalGames.psd1
+            #       Test-GitAttributesFile -Verbose
 
-            - name: Run cspell config linter
-              if: (success() || failure()) && steps.dependencies.outcome == 'success'
-              run: |
-                  Import-Module ./modules/TerminalGames.psd1
-                  Test-CSpellConfigurationFile -Verbose
+            # - name: Run cspell config linter
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success'
+            #   run: |
+            #       Import-Module ./modules/TerminalGames.psd1
+            #       Test-CSpellConfigurationFile -Verbose
 
-            - name: Run prettierignore linter
-              if: (success() || failure()) && steps.dependencies.outcome == 'success'
-              run: |
-                  Import-Module ./modules/TerminalGames.psd1
-                  Test-PrettierIgnoreFile -Verbose
+            # - name: Run prettierignore linter
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success'
+            #   run: |
+            #       Import-Module ./modules/TerminalGames.psd1
+            #       Test-PrettierIgnoreFile -Verbose
 
-            - name: Run cspell
-              if: (success() || failure()) && steps.dependencies.outcome == 'success'
-              run: |
-                  Import-Module ./modules/TerminalGames.psd1
-                  Test-CodeUsingCSpell -Verbose
+            # - name: Run cspell
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success'
+            #   run: |
+            #       Import-Module ./modules/TerminalGames.psd1
+            #       Test-CodeUsingCSpell -Verbose
 
-            - name: Run prettier
-              if: (success() || failure()) && steps.dependencies.outcome == 'success'
-              run: |
-                  Import-Module ./modules/TerminalGames.psd1
-                  Test-CodeUsingPrettier -Verbose
+            # - name: Run prettier
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success'
+            #   run: |
+            #       Import-Module ./modules/TerminalGames.psd1
+            #       Test-CodeUsingPrettier -Verbose
 
-            - name: Run PSScriptAnalyzer
-              if: (success() || failure()) && steps.dependencies.outcome == 'success'
-              run: |
-                  Import-Module ./modules/TerminalGames.psd1
-                  Test-CodeUsingPSScriptAnalyzer -Verbose
+            # - name: Run PSScriptAnalyzer
+            #   if: (success() || failure()) && steps.dependencies.outcome == 'success'
+            #   run: |
+            #       Import-Module ./modules/TerminalGames.psd1
+            #       Test-CodeUsingPSScriptAnalyzer -Verbose
 
             - name: Run clang-tidy and clang-format
               if: (success() || failure()) && steps.dependencies.outcome == 'success'
